### PR TITLE
Adds in new type of change and more information about multiple ticket…

### PR DESCRIPTION
**Pull request by JudsonStevens**
…s in one PR

### CODE REVIEW

**Comment by JudsonStevens** [comment]
For reference, multiple tickets have to be referenced in the title - see this Issue for why https://github.com/atlassian/github-for-jira/issues/765.

**Comment by JudsonStevens** [comment]
@RobertCalise - pinging you real quick about this one, just want to make sure you are aware and in agreement about multiple ticket PRs.

**Comment by RobertCalise** [comment]
@JudsonStevens do we want them at the end of the title? I'm assuming this means excluding details about the secondary ticket item as well.

For a multi-ticket PR, I would err on the side of something like `PIPELINE-6, PIPELINE-7: Fixes Thing no. 1 and Thing no. 2`, where the text can be a more freeform summary of the ticket titles rather than an exact title. Thoughts?

**Comment by JudsonStevens** [comment]
I was thinking keeping the main ticket name/description in the title and appending the others to the end, and then describing or using the name/description in the body of the PR for the related tickets.

**Comment by RobertCalise** [comment]
As long as there is a clear delineation between primary ticket and secondary ones, I'm fine with this. And if there isn't, I guess it should be separate PRs anyway. Approved.

**Pull request merged**
